### ISSUE TITLE
Hate speech identification

### ISSUE THREAD

**Issue by t-davidson** [niderhoff/nlp-datasets#1]
Hate speech link broken. Correct reference is https://github.com/t-davidson/hate-speech-and-offensive-language (CF actually released a subset of our labelled data without notifying us, we released a larger set of labeled data that you can access using the link here).

**Comment by niderhoff** [comment]
Hi,

I just updated the link to your github. Thank you for your contribution.

**Comment by t-davidson** [comment]
Great, thanks!
