### ISSUE TITLE
dataset with people's dialogues

### ISSUE THREAD

**Issue by jasperDD** [niderhoff/nlp-datasets#14]
Tell me, are there datasets with people's dialogues? I'm looking for it to simulate the model of people's communication using BIG DATA. For example, often people communicate so

     First_man(question)     Second_man (answer)                       
[1,] "how are you" "Fine, thank you, and how are you?"
Are there such data? I.E. data of everyday communication between people

**Comment by e-budur** [comment]
You may have a look at https://breakend.github.io/DialogDatasets/

jasperDD <notifications@github.com> şunları yazdı (25 Oca 2019 16:14):

**Comment by jasperDD** [comment]
e-budur , yes, this is that i found. Thank you.:)
