### ISSUE TITLE
Gutenberg dataset

### ISSUE THREAD

**Issue by gokceneraslan** [niderhoff/nlp-datasets#18]
Hi,

https://github.com/pgcorpus/gutenberg is a very cool resource which contains scripts to download and preprocess the Gutenberg corpus. There is also an accompanying paper by @martingerlach and @fontclos https://arxiv.org/abs/1812.08092. I think it'd be nice to add this to the list.

**Comment by niderhoff** [comment]
Looks like a good resource. Thank you, I added it.
