### ISSUE TITLE
Political Social Media data set now points to paid service Appen instead of Crowdflower

### ISSUE THREAD

**Issue by dyerdave-cvs** [niderhoff/nlp-datasets#29]
The political data set now points here instead of crowdflower.

https://appen.com/resources/datasets/

**Comment by jotaf98** [comment]
Same with the "Identifying key phrases in text", and "Objective truths of sentences/concept pairs" datasets!

Looks like they made all the datasets private suddenly.

Are there copies of the source data anywhere else?

**Comment by niderhoff** [comment]
I removed them, thanks for noticing.
