### ISSUE TITLE
Multiple Historical News Headlines Datasets

### ISSUE THREAD

**Issue by therohk** [niderhoff/nlp-datasets#4]
Some datasets you can review and add. (disclaimer: authored by me), Specifically the 4 regarding headlines and 1 regarding urban dictionary. Thanks!

https://www.kaggle.com/therohk/datasets

**Comment by niderhoff** [comment]
Hey, you can make a pull requests yourself, adding each dataset in its own row and then i can merge it into the main repo.

**Comment by therohk** [comment]
Have added a pull request. Thanks.
