### ISSUE TITLE
Missing metadata for Amazon Reviews dataset

### ISSUE THREAD

**Issue by hiteshvaidya** [niderhoff/nlp-datasets#7]
Hello @niderhoff 

Thank you so much for releasing these datasets. I downloaded the 'Amazon reviews' dataset. But I am unable to make any sense out of it. Its a mixture of review title and review text for all the products on amazon. There is no classification as such. 
I was looking for dataset of reviews for mobile phones. And such particular reviews are all mixed up in the given dataset. Also, there is no labeling done as such.
Could you please any possible solution to these problems?

Thanks again

**Comment by niderhoff** [comment]
Hello @hiteshvaidya,

first and foremost I have to say that I am neither author nor the maintainer of said dataset. I merely created this list with links to datasets I found in my research. 

When you click the link there is a list of different documents, including:

- reviews for different categories 
- category information for all products
- also an example code on how to parse it in python.

I have not used the dataset myself, so I can offer no help. If the information provided in the link does not suffice you would have to ask the authors or google for any solution made by somebody who used the dataset before.

Best,
Nicolas
